name = "ASKEM_Evaluation_Staging"
uuid = "d1df7db2-046b-4eac-b11d-ddc9c5f134b0"
authors = ["JuliaHub"]
version = "1.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
